# Generated by Django 5.0.6 on 2024-05-30 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='forum',
            new_name='branch',
        ),
    ]
