# Generated by Django 5.0.6 on 2024-05-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_rename_forum_comment_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='branch_media'),
        ),
        migrations.AddField(
            model_name='comment',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='comment_media'),
        ),
    ]
